project_id = "zpytenapldiyxvjrntrm"

[functions.ai-chat]
verify_jwt = true

[functions.content-processor]
verify_jwt = true

[functions.video-summarizer]
verify_jwt = true

[functions.gmail-integration]
verify_jwt = true

[functions.document-summarizer]
verify_jwt = false